" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=DejaVu\ Sans\ Mono:h18       " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T               " Hide toolbar.
set background=dark             " Background.
set lines=60 columns=130          " Window dimensions.
set guicursor=a:hor1

set guioptions-=r                 " Don't show right scrollbar


